# 出站策略, 根据自己情况调整每个策略里分组排序, 增删都可以, 比如把美国自动放到第一个, 比如删除香港故转, 注意别漏掉表情逗号等.
# 如果相应分组没有筛选到对应的国家, 请根据自己节点名字调整筛选关键字.
# 没有再使用锚点, 是考虑很多新手修改难度, 这样新手修改某个分组更容易些.
proxy-groups:
  - {
      name: 🚀 默认代理,
      type: select,
      proxies:
        [
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 👾 Steam,
      type: select,
      proxies:
        [
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 📹 YouTube,
      type: select,
      proxies:
        [
          🔯 美国故转,
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          ♻️ 美国自动,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 🍀 Google,
      type: select,
      proxies:
        [
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 🤖 ChatGPT,
      type: select,
      proxies:
        [
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 👨🏿‍💻 GitHub,
      type: select,
      proxies:
        [
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 🐬 OneDrive,
      type: select,
      proxies:
        [
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 🪟 Microsoft,
      type: select,
      proxies:
        [
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 🎵 TikTok,
      type: select,
      proxies:
        [
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 📲 Telegram,
      type: select,
      proxies:
        [
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 🎥 NETFLIX,
      type: select,
      proxies:
        [
          🔯 狮城故转,
          🔯 香港故转,
          🔯 日本故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 🎥 TED,
      type: select,
      proxies:
        [
          🔯 狮城故转,
          🔯 香港故转,
          🔯 日本故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: ✈️ Speedtest,
      type: select,
      proxies:
        [
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 💶 PayPal,
      type: select,
      proxies:
        [
          🔯 日本故转,
          🔯 香港故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - { name: 🍎 Apple, type: select, proxies: [直连, 🚀 默认代理] }
  - { name: 🎯 直连, type: select, proxies: [直连, 🚀 默认代理] }
  - {
      name: 🐟 漏网之鱼,
      type: select,
      proxies:
        [
          🔯 香港故转,
          🔯 日本故转,
          🔯 狮城故转,
          🔯 美国故转,
          ♻️ 香港自动,
          ♻️ 日本自动,
          ♻️ 狮城自动,
          ♻️ 美国自动,
          ♻️ 自动选择,
          🇭🇰 香港节点,
          🇯🇵 日本节点,
          🇸🇬 狮城节点,
          🇺🇲 美国节点,
          🌐 全部节点,
          直连,
        ],
    }
  - {
      name: 🇭🇰 香港节点,
      type: select,
      include-all: true,
      filter: "(?i)港|hk|hongkong|hong kong",
    }
  - {
      name: 🇯🇵 日本节点,
      type: select,
      include-all: true,
      filter: "(?i)日|jp|japan",
    }
  - {
      name: 🇸🇬 狮城节点,
      type: select,
      include-all: true,
      filter: "(?i)新加坡|坡|狮城|SG|Singapore",
    }
  - {
      name: 🇺🇲 美国节点,
      type: select,
      include-all: true,
      filter: "(?i)美|us|unitedstates|united states",
    }
  - {
      name: 🔯 香港故转,
      type: fallback,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$",
    }
  - {
      name: 🔯 日本故转,
      type: fallback,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$",
    }
  - {
      name: 🔯 狮城故转,
      type: fallback,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(台|日|韩|深|美)).)*$",
    }
  - {
      name: 🔯 美国故转,
      type: fallback,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(美|US|(?i)States|America))^((?!(港|台|韩|新|日)).)*$",
    }
  - {
      name: ♻️ 香港自动,
      type: url-test,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$",
    }
  - {
      name: ♻️ 日本自动,
      type: url-test,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$",
    }
  - {
      name: ♻️ 狮城自动,
      type: url-test,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(港|台|韩|日|美)).)*$",
    }
  - {
      name: ♻️ 美国自动,
      type: url-test,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?=.*(美|US|(?i)States|America))^((?!(港|台|日|韩|新)).)*$",
    }
  - {
      name: ♻️ 自动选择,
      type: url-test,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "^((?!(直连)).)*$",
    }
  - { name: 🌐 全部节点, type: select, include-all: true }
