# è§„åˆ™åŒ¹é…
rules:
  # 1. æœ¬åœ°/ç§æœ‰
  - RULE-SET,private_ip,ç›´è¿,no-resolve
  - RULE-SET,private_domain,ç›´è¿

  ## 1.1 LOL
  - PROCESS-NAME,WeGame.exe,DIRECT
  - PROCESS-NAME,TencentWeGame.exe,DIRECT
  - PROCESS-NAME,LeagueClient.exe,DIRECT
  - PROCESS-NAME,LeagueClientUx.exe,DIRECT
  - PROCESS-NAME,LeagueClientUxRender.exe,DIRECT
  - PROCESS-NAME,League of Legends.exe,DIRECT
  - PROCESS-NAME,TencentAntiCheat.exe,DIRECT
  - PROCESS-NAME,TclsClient.exe,DIRECT
  - PROCESS-NAME,TclsService.exe,DIRECT
  - RULE-SET,lol-cn,DIRECT

  # 2. ç²¾å‡†åŸŸåè§„åˆ™(é¡ºåºéšæ„)
  - RULE-SET,ted_domain,ğŸ¥ TED
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,apple_domain,ç›´è¿
  - RULE-SET,ai,ğŸ¤– ChatGPT
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,onedrive_domain,ğŸ¬ OneDrive
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  - RULE-SET,speedtest_domain,âœˆï¸ Speedtest
  - RULE-SET,steam_CN,ç›´è¿
  - RULE-SET,steam,ğŸ‘¾ Steam
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,tiktok_domain,ğŸµ TikTok

  # 3. IP è§„åˆ™(å¿…é¡»åœ¨åŸŸåè§„åˆ™å)
  - RULE-SET,apple_ip,ç›´è¿
  - RULE-SET,google_ip,ğŸ€ Google,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX,no-resolve
  - RULE-SET,telegram_ip,ğŸ“² Telegram,no-resolve

  # 4. å›½å¤– IP/åŸŸåå…œåº•
  - RULE-SET,gfw_domain,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†

  # 5. å›½å†…å…œåº•
  - GEOIP,CN,ğŸ¯ ç›´è¿
  - RULE-SET,cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,cn_ip,ğŸ¯ ç›´è¿

  # 6. æœ€ç»ˆå…œåº•
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
